package enums;

public enum BaseTypeJewelry {
	JET_AMULET,CORAL_AMULET,PAUA_AMULET,AMBER_AMULET,JADE_AMULET,LAPIS_AMULET,GOLD_AMULET,TURQUOISE_AMULET,AGATE_AMULET,CITRINE_AMULET,ONYX_AMULET,CHAIN_BELT,RUSTIC_SASH,HEAVY_BELT,LEATHER_BELT,GOLDEN_OBI,CLOTH_BELT,STUDDED_BELT,IRON_RING,CORAL_RING,PAUA_RING,TOPAZ_RING,SAPPHIRE_RING,RUBY_RING,GOLD_RING,GOLDEN_HOOP,TWO_STONE_RING,MOONSTONE_RING,DIAMOND_RING,PRISMATIC_RING,AMETHYST_RING,UNSET_RING

}
