package enums;

public enum ItemClass {
	LIFE_FLASKS,MANA_FLASKS,HYBRID_FLASKS,CURRENCY,AMULETS,RINGS,CLAWS,DAGGERS,WANDS,ONE_HAND_SWORDS,THRUSTING_ONE_HAND_SWORDS,ONE_HAND_AXES,ONE_HAND_MACES,BOWS,STAVES,TWO_HAND_SWORDS,TWO_HAND_AXES,TWO_HAND_MACES,ACTIVE_SKILL_GEMS,SUPPORT_SKILL_GEMS,QUIVERS,BELTS,GLOVES,BOOTS,BODY_ARMOURS,HELMETS,SHIELDS,STACKABLE_CURRENCY,QUEST_ITEMS,SCEPTRES,UTILITY_FLASKS,MAPS,FISHING_RODS,MAP_FRAGMENTS,HIDEOUT_DOODADS,MICROTRANSACTIONS,JEWEL,DIVINATION_CARD
}
